import { Webhook, Sparkles, Database, Send, GitBranch } from "lucide-react"

export const flowNodeOptions = [
  {
    type: "decision",
    title: "If & Else",
    icon: "branch",
    tag: "Condition",
    description: "Route the flow based on a condition.",
    label: "If & Else",
    Icon: GitBranch,
    iconClassName: "text-amber-500",
  },
  {
    type: "workflow",
    title: "Webhook Hook",
    icon: "webhook",
    tag: "Trigger",
    description: "Receive real-time external HTTP payload.",
    label: "Trigger",
    Icon: Webhook,
    iconClassName: "text-emerald-500",
  },
  {
    type: "workflow",
    title: "AI Transform",
    icon: "ai",
    tag: "AI Task",
    description: "Process content with LLM model.",
    label: "AI Prompt",
    Icon: Sparkles,
    iconClassName: "text-purple-500",
  },
  {
    type: "workflow",
    title: "Database Store",
    icon: "database",
    tag: "Storage",
    description: "Persist records into database.",
    label: "Database",
    Icon: Database,
    iconClassName: "text-blue-500",
  },
  {
    type: "action",
    title: "Quick Action",
    icon: "send",
    tag: "Action",
    description: "Send notification or webhook.",
    label: "Action",
    Icon: Send,
    iconClassName: "text-amber-500",
  },
]
